### ISSUE TITLE
clock-rs doesn't run

### ISSUE THREAD

**Issue by Victinijr** [Oughie/clock-rs#4]
running arch with openbox on a surface pro 7. installed clock-rs but when i ran it, it said zsh: command not found: clock-rs.

**Comment by Oughie** [comment]
Have you installed `clock-rs` via `$ cargo install clock-rs` or did you compile the repository from source? If so, did you run `$ cargo build --release` which places the executable in the `./target/release`) directory?

**Comment by Victinijr** [comment]
i installed via `$ cargo install clock-rs
`

**Comment by Oughie** [comment]
Is the binary located inside the `$HOME/.cargo/bin` directory? Could you perhaps try compiling it by source? After you clone the repo, build it using ` $cargo build --release` and then run `$ ./target/release/clock-rs`

**Comment by Victinijr** [comment]
when i ran `$ cargo build --release` it gave an error saying `**error**: could not find 'Cargo.toml' in 'home/<me>' or any other parent directory`

**Comment by Oughie** [comment]
You need to first use the `cd` command to change into the cloned directory where the Cargo.toml is located?

**Comment by Victinijr** [comment]
> Is the binary located inside the `$HOME/.cargo/bin` directory? If it's not, could you perhaps try compiling it by source? After you clone the repo, build it using `$ cargo build --release` and then run `$ ./target/release/clock-rs`

the binary is in '$HOME/.cargo/bin' sorry i just noticed

**Comment by Oughie** [comment]
Is `$HOME/.cargo/bin` added to `$PATH`? Find out if it is by printing it using `echo $PATH` _or_ `tr ':' '\n' <<< "$PATH"` for an easy-to-read output.

**Comment by Victinijr** [comment]
No

**Comment by Oughie** [comment]
You should be able to do so by adding `export PATH="$HOME/.cargo/bin:$PATH"` to your `.zshrc` and then restarting your terminal.

**Comment by Victinijr** [comment]
> You should be able to do so by adding `export PATH="$HOME/.cargo/bin:$PATH"` to your `.zshrc` and then restarting your terminal.

so i just run the command?

**Comment by Oughie** [comment]
Awesome :). Since the beginning, I'm still  unsure whether you are trolling, since you use Arch and also have zero activity on your profile. But I'm glad this issue is resolved.
